# Netlify configuration file
# This file specifies build settings and redirects for your Netlify deployment

[build]
  publish = "public"  # Publish the public directory
  command = ""  # No build command needed for a pre-built static site
  functions = "netlify/functions"  # Directory where your Netlify Functions are stored

[build.environment]
  NODE_VERSION = "18"  # Set Node.js version for the build

# Global functions settings (all functions can access utils folder)
[functions]
  included_files = ["utils/**"]

# Specific config for stripe webhook
[functions."stripe-webhook"]
  type = "raw"
  included_files = ["utils/**"]
  external_node_modules = ["stripe", "pg"]

# Production context
[context.production.environment]
  NODE_ENV = "production"

# Deploy Preview context
[context.deploy-preview.environment]
  NODE_ENV = "staging"

# Branch Deploy context
[context.branch-deploy.environment]
  NODE_ENV = "staging"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for all routes
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.stripe.com; script-src 'self' 'unsafe-inline' https://*.stripe.com; frame-src https://*.stripe.com; img-src 'self' data: https://*.stripe.com;"

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.images]
  compress = true

# Optional 404 page
# [[redirects]]
#   from = "/*"
#   to = "/404/index.html"
#   status = 404
